/*
 * generated by Xtext
 */
package de.xtext.mgse.aos;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AgeOfScalaRuntimeModule extends de.xtext.mgse.aos.AbstractAgeOfScalaRuntimeModule {

}
