/*
* generated by Xtext
*/
package de.xtext.mgse.aos.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.xtext.mgse.aos.services.AgeOfScalaGrammarAccess;

public class AgeOfScalaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AgeOfScalaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.xtext.mgse.aos.parser.antlr.internal.InternalAgeOfScalaParser createParser(XtextTokenStream stream) {
		return new de.xtext.mgse.aos.parser.antlr.internal.InternalAgeOfScalaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Action";
	}
	
	public AgeOfScalaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AgeOfScalaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
