/*
* generated by Xtext
*/
package de.xtext.mgse.aos.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AgeOfScalaAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/xtext/mgse/aos/parser/antlr/internal/InternalAgeOfScala.tokens");
	}
}
